"""empty message

Revision ID: 38c312e3a691
Revises: a9fb4eb92852
Create Date: 2020-07-22 12:17:53.602650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c312e3a691'
down_revision = 'a9fb4eb92852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
